[package]
name = "humpback"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
tokio = { version = "1.0", features = ["full"] }
