[package]
name = "humpback"
version = "0.5.0"
edition = "2024"

[profile.release]
debug = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
tokio = { version = "1.0", features = ["full"] }
deno_core = "0.311"
reqwest = "0.12.22"
